# Generated by Django 5.0.4 on 2024-05-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opd_app', '0002_comments_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='author_name',
        ),
    ]
