# Generated by Django 5.0.4 on 2024-05-16 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_app', '0003_remove_comments_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
