# Generated by Django 5.0.4 on 2024-05-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_app', '0004_path_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default=0, upload_to='avatar/'),
            preserve_default=False,
        ),
    ]
