# Generated by Django 5.0.4 on 2024-05-21 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_app', '0005_users_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd_app.path')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd_app.users')),
            ],
        ),
    ]
